### ISSUE TITLE
Why inherit the box-model?

### ISSUE THREAD

**Issue by mirisuzanne** [zellwk/css-reset#2]
This is cool! I'm gonna steal your ideas here :) 

Can you explain why you chose the `box-sizing: inherit` approach? I find it very strange to inherit a layout property – it feels similar to inheriting margins or padding. When I (rarely) want to change `box-sizing`, it is always for a specific element in a specific situation (like a container that should have a certain inner width) – never for an element*-and-all-its-decendants*. The `* { box-sizing: border-box; }` approach solves for that with less code, and you can still use `inherit` for specific use-cases, as needed.

**Comment by dallanlee** [comment]
> Can you explain why you chose the `box-sizing: inherit` approach?

@mirisuzanne This is fairly common so you could do a search for more info. Here are two links you'd come across with a Google search: https://css-tricks.com/box-sizing/#article-header-id-6 https://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/

**Comment by mirisuzanne** [comment]
Yeah, I'm well aware that it's common, and I've read all the articles. But they are way out of date, and I'm confused why people still do it.

It is straight-forward and clear how to override the universal selector with a new scoped setting for components:

```css
* { box-sizing: border-box; }
.olschool * { box-sizing: content-box; }
```

You could even make that into a utility class. But it is not clear or readable when you want to create a one-off with the inherited version:

```css
html { box-sizing: border-box; }
* { box-sizing: inherit; }

.one-off { box-sizing:  content-box; }
/* also need to override direct children, to flip it back…? */
.one-off > * { box-sizing: border-box; }
```

It's more code all-around to do what should be straight-forward.
